[package]
name = "program"
version = "0.1.0"
authors = ["Titus <properllerbucher@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "my_benchmark"
harness = false

[dependencies]
criterion = "0.3.1"
